services:
  ci:
    image: ghcr.io/sigmajuniory/stairs-light-ci:latest
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: bash
  format:
    image: ghcr.io/sigmajuniory/stairs-light-ci:latest
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ./scripts/formatter.sh