name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Static Code Analysis (zamiast clang-format)
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      
      - name: Run static analysis
        run: |
          mkdir static_analysis_logs
          pio check -e native --fail-on-defect=medium &> static_analysis_logs/results.txt
      
      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pio-check-results
          path: static_analysis_logs/ 

  # Job 2: Testy native
  native-tests:
    name: Native Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PlatformIO
        run: pip install platformio
      
      - name: Run native tests
        run: |
          mkdir -p unit_tests_logs
          pio test -e native &> unit_tests_logs/results.txt

      - name: Upload tests results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pio-tests-results
          path: unit_tests_logs/ 
